on:
  push:
    branches:
      - '*'
jobs:
  build-all-examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: hello-world
        run: pushd hello-world && ./gradlew test && popd
      - name: json-api
        run: pushd json-api && ./gradlew test && popd
      - name: openapi
        run: pushd openapi && ./gradlew test && popd
      - name: web-content
        run: pushd web-content && ./gradlew test && popd
